/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Sistema.Frames;

import java.awt.Container;

/**
 *
 * @author USUARIO
 */
public class MenuMateria extends javax.swing.JPanel {

    /**
     * Creates new form MenuMateria
     */
    public MenuMateria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtOpciones = new javax.swing.JLabel();
        MateriaRegistrarPanel = new javax.swing.JPanel();
        txtRegistrarMateri = new javax.swing.JLabel();
        PanelBuscarMateria = new javax.swing.JPanel();
        UsuarioTxt1 = new javax.swing.JLabel();
        PnlEliminarMateria = new javax.swing.JPanel();
        UsuarioTxt3 = new javax.swing.JLabel();
        PanelUpDateMateria = new javax.swing.JPanel();
        UsuarioTxt2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        txtOpciones.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txtOpciones.setForeground(new java.awt.Color(96, 131, 165));
        txtOpciones.setText("MENU  DE MATERIA");

        MateriaRegistrarPanel.setBackground(new java.awt.Color(255, 255, 255));
        MateriaRegistrarPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MateriaRegistrarPanel.setPreferredSize(new java.awt.Dimension(160, 160));
        MateriaRegistrarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MateriaRegistrarPanelMouseClicked(evt);
            }
        });

        txtRegistrarMateri.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtRegistrarMateri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRegistrarMateri.setText("Registro Materia");

        javax.swing.GroupLayout MateriaRegistrarPanelLayout = new javax.swing.GroupLayout(MateriaRegistrarPanel);
        MateriaRegistrarPanel.setLayout(MateriaRegistrarPanelLayout);
        MateriaRegistrarPanelLayout.setHorizontalGroup(
            MateriaRegistrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MateriaRegistrarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtRegistrarMateri, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        MateriaRegistrarPanelLayout.setVerticalGroup(
            MateriaRegistrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MateriaRegistrarPanelLayout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(txtRegistrarMateri)
                .addGap(17, 17, 17))
        );

        PanelBuscarMateria.setBackground(new java.awt.Color(255, 255, 255));
        PanelBuscarMateria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelBuscarMateria.setPreferredSize(new java.awt.Dimension(160, 160));

        UsuarioTxt1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        UsuarioTxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UsuarioTxt1.setText("Buscar Materia");

        javax.swing.GroupLayout PanelBuscarMateriaLayout = new javax.swing.GroupLayout(PanelBuscarMateria);
        PanelBuscarMateria.setLayout(PanelBuscarMateriaLayout);
        PanelBuscarMateriaLayout.setHorizontalGroup(
            PanelBuscarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBuscarMateriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UsuarioTxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelBuscarMateriaLayout.setVerticalGroup(
            PanelBuscarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBuscarMateriaLayout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(UsuarioTxt1)
                .addGap(17, 17, 17))
        );

        PnlEliminarMateria.setBackground(new java.awt.Color(255, 255, 255));
        PnlEliminarMateria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PnlEliminarMateria.setPreferredSize(new java.awt.Dimension(160, 160));

        UsuarioTxt3.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        UsuarioTxt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UsuarioTxt3.setText("Eliminar Materia ");

        javax.swing.GroupLayout PnlEliminarMateriaLayout = new javax.swing.GroupLayout(PnlEliminarMateria);
        PnlEliminarMateria.setLayout(PnlEliminarMateriaLayout);
        PnlEliminarMateriaLayout.setHorizontalGroup(
            PnlEliminarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlEliminarMateriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UsuarioTxt3, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        PnlEliminarMateriaLayout.setVerticalGroup(
            PnlEliminarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlEliminarMateriaLayout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(UsuarioTxt3)
                .addGap(17, 17, 17))
        );

        PanelUpDateMateria.setBackground(new java.awt.Color(255, 255, 255));
        PanelUpDateMateria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelUpDateMateria.setPreferredSize(new java.awt.Dimension(160, 160));

        UsuarioTxt2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        UsuarioTxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UsuarioTxt2.setText("Actualizar datos");

        javax.swing.GroupLayout PanelUpDateMateriaLayout = new javax.swing.GroupLayout(PanelUpDateMateria);
        PanelUpDateMateria.setLayout(PanelUpDateMateriaLayout);
        PanelUpDateMateriaLayout.setHorizontalGroup(
            PanelUpDateMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUpDateMateriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UsuarioTxt2, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelUpDateMateriaLayout.setVerticalGroup(
            PanelUpDateMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUpDateMateriaLayout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(UsuarioTxt2)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtOpciones)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(100, 100, 100)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(MateriaRegistrarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(PanelBuscarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(PanelUpDateMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(PnlEliminarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(txtOpciones)
                    .addGap(29, 29, 29)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MateriaRegistrarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PanelBuscarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PanelUpDateMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PnlEliminarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MateriaRegistrarPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MateriaRegistrarPanelMouseClicked
        RegistrarMateriaPanel mou = new RegistrarMateriaPanel();
        mou.setSize(670, 580);
        mou.setLocation(0, 0);

        Container container = this.getParent();
        container.remove(this);
        container.add(mou);
        container.validate();
        container.repaint();
    }//GEN-LAST:event_MateriaRegistrarPanelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MateriaRegistrarPanel;
    private javax.swing.JPanel PanelBuscarMateria;
    private javax.swing.JPanel PanelUpDateMateria;
    private javax.swing.JPanel PnlEliminarMateria;
    private javax.swing.JLabel UsuarioTxt1;
    private javax.swing.JLabel UsuarioTxt2;
    private javax.swing.JLabel UsuarioTxt3;
    private javax.swing.JLabel txtOpciones;
    private javax.swing.JLabel txtRegistrarMateri;
    // End of variables declaration//GEN-END:variables
}
