/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Sistema.Frames;

import Sistema.Frames.Curso.MenuCurso;
import Sistema.Frames.Principal.JPrincipal;
import java.awt.Container;

/**
 *
 * @author USUARIO
 */
public class MenuPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form MateriasPanel
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OpcionesTxt = new javax.swing.JLabel();
        UsuarioPanel = new javax.swing.JPanel();
        UsuarioTxt = new javax.swing.JLabel();
        InicioIcono2 = new javax.swing.JLabel();
        MateriaPanel = new javax.swing.JPanel();
        UsuarioTxt1 = new javax.swing.JLabel();
        InicioIcono1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OpcionesTxt.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        OpcionesTxt.setForeground(new java.awt.Color(96, 131, 165));
        OpcionesTxt.setText("MENU DE OPCIONES");
        add(OpcionesTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, 20));

        UsuarioPanel.setBackground(new java.awt.Color(255, 255, 255));
        UsuarioPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UsuarioPanel.setPreferredSize(new java.awt.Dimension(197, 200));
        UsuarioPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsuarioPanelMouseClicked(evt);
            }
        });

        UsuarioTxt.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        UsuarioTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UsuarioTxt.setText("USUARIO");

        InicioIcono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/Imagenes/birrete.png")));

        javax.swing.GroupLayout UsuarioPanelLayout = new javax.swing.GroupLayout(UsuarioPanel);
        UsuarioPanel.setLayout(UsuarioPanelLayout);
        UsuarioPanelLayout.setHorizontalGroup(
            UsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(UsuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(UsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsuarioPanelLayout.createSequentialGroup()
                    .addContainerGap(30, Short.MAX_VALUE)
                    .addComponent(InicioIcono2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(22, 22, 22)))
        );
        UsuarioPanelLayout.setVerticalGroup(
            UsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsuarioPanelLayout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(UsuarioTxt)
                .addGap(25, 25, 25))
            .addGroup(UsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(UsuarioPanelLayout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(InicioIcono2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(48, Short.MAX_VALUE)))
        );

        add(UsuarioPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        MateriaPanel.setBackground(new java.awt.Color(255, 255, 255));
        MateriaPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MateriaPanel.setPreferredSize(new java.awt.Dimension(197, 200));
        MateriaPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MateriaPanelMouseClicked(evt);
            }
        });

        UsuarioTxt1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        UsuarioTxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UsuarioTxt1.setText("MATERIA");

        InicioIcono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/Imagenes/CursoInternet.png")));

        javax.swing.GroupLayout MateriaPanelLayout = new javax.swing.GroupLayout(MateriaPanel);
        MateriaPanel.setLayout(MateriaPanelLayout);
        MateriaPanelLayout.setHorizontalGroup(
            MateriaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MateriaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(UsuarioTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(MateriaPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(InicioIcono1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        MateriaPanelLayout.setVerticalGroup(
            MateriaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MateriaPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(InicioIcono1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UsuarioTxt1)
                .addGap(24, 24, 24))
        );

        add(MateriaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuarioPanelMouseClicked
        MenuOpcionesUser mu = new MenuOpcionesUser();
        mu.setSize(890, 750);
        mu.setLocation(0, 0);

        // Obtén el contenedor principal
        Container contenedorPrincipal = this.getParent();

        // Elimina el panel actual
        contenedorPrincipal.remove(this);

        // Agrega el nuevo panel (MenuUsuario)
        contenedorPrincipal.add(mu);

        // Valida y repinta el contenedor principal
        contenedorPrincipal.validate();
        contenedorPrincipal.repaint();
    }//GEN-LAST:event_UsuarioPanelMouseClicked

    private void MateriaPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MateriaPanelMouseClicked
        // TODO add your handling code here:

        MenuCurso mc = new MenuCurso();
        mc.setSize(890, 750);
        mc.setLocation(0, 0);

        // Obtén el contenedor principal
        Container contenedorPrincipal = this.getParent();

        // Elimina el panel actual
        contenedorPrincipal.remove(this);

        // Agrega el nuevo panel (MenuUsuario)
        contenedorPrincipal.add(mc);

        // Valida y repinta el contenedor principal
        contenedorPrincipal.validate();
        contenedorPrincipal.repaint();
    }//GEN-LAST:event_MateriaPanelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InicioIcono1;
    private javax.swing.JLabel InicioIcono2;
    private javax.swing.JPanel MateriaPanel;
    private javax.swing.JLabel OpcionesTxt;
    private javax.swing.JPanel UsuarioPanel;
    private javax.swing.JLabel UsuarioTxt;
    private javax.swing.JLabel UsuarioTxt1;
    // End of variables declaration//GEN-END:variables
}
