/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Sistema.Frames;

import java.awt.Container;

/**
 *
 * @author USUARIO
 */
public class MenuMateria extends javax.swing.JPanel {

    /**
     * Creates new form MenuMateria
     */
    public MenuMateria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtOpciones = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtOpciones.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txtOpciones.setForeground(new java.awt.Color(96, 131, 165));
        txtOpciones.setText("MENU  DE MATERIA");
        add(txtOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 88, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel txtOpciones;
    // End of variables declaration//GEN-END:variables
}
