/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Sistema.Frames;

import java.awt.Container;

/**
 *
 * @author USUARIO
 */
public class MenuProfesor extends javax.swing.JPanel {

    /**
     * Creates new form MenuUsuario
     */
    public MenuProfesor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OpcionesTxt = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(669, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OpcionesTxt.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        OpcionesTxt.setForeground(new java.awt.Color(96, 131, 165));
        OpcionesTxt.setText("MENU  DE PROFESOR:D");
        add(OpcionesTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel OpcionesTxt;
    // End of variables declaration//GEN-END:variables
}
