/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Sistema.Frames.Matricula;

import Sistema.Clases.*;



/**
 *
 * @author USUARIO
 */
public class MatriculaPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportePanel
     */
    public MatriculaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        matriculaPanel1 = new Sistema.MatriculaPrueba.MatriculaPanel2();
        btnRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        id_alumnoM = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CboxCursos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        CboxSecciones = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtFechaM = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtestado = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(670, 580));
        setPreferredSize(new java.awt.Dimension(670, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrar.setText("MATRICULAR");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 640, 130, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PROCESO DE MATRÍCULA");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 320, 70));

        id_alumnoM.setText("Ingrese el ID del alumno");
        id_alumnoM.setMinimumSize(new java.awt.Dimension(142, 22));
        add(id_alumnoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 260, 50));

        jLabel2.setText("ID Alumno:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 220, 30));

        jLabel3.setText("Curso a matricular:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 220, 30));

        CboxCursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CboxCursos.setMinimumSize(new java.awt.Dimension(142, 22));
        CboxCursos.setPreferredSize(new java.awt.Dimension(142, 22));
        add(CboxCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 260, 50));

        jLabel4.setText("Sección:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 220, 30));

        CboxSecciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CboxSecciones.setPreferredSize(new java.awt.Dimension(142, 22));
        add(CboxSecciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 260, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 430, 540));

        jLabel5.setText("Fecha");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 260, -1));

        txtFechaM.setText("fecha");
        add(txtFechaM, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 260, 40));

        jLabel6.setText("Estado");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 60, -1));

        txtestado.setText("Estado");
        add(txtestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 260, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        try {
            int idEstudiante;
            idEstudiante = Integer.parseInt(id_alumnoM.getText());
            daoMatrícula matricula = new daoMatrícula();
            //OJOOOOOOOOOOOOOOOO
            Matricula m1 = new Matricula(3, 0, idEstudiante, txtFechaM.getText(), txtestado.getText());
            

            if(matricula.realizarMatricula(m1)){
                System.out.println("Se realizo la matricula exitosamente");
            } else {
                System.out.println("Error al realizar matricula");
            }
            
        } catch (Exception e) {
            System.out.println("ERROR");
        }    // TODO add your handling code here:
     
    }//GEN-LAST:event_btnRegistrarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboxCursos;
    private javax.swing.JComboBox<String> CboxSecciones;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JTextField id_alumnoM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private Sistema.MatriculaPrueba.MatriculaPanel2 matriculaPanel1;
    private javax.swing.JTextField txtFechaM;
    private javax.swing.JTextField txtestado;
    // End of variables declaration//GEN-END:variables
}
