/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Sistema.Frames.Matricula;

import Sistema.Clases.*;
import Sistema.Frames.ErrorDialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;



/**
 *
 * @author USUARIO
 */
public class MatriculaPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportePanel
     */
    public MatriculaPanel() {
        initComponents();
        llenarCbxCurso();
        llenarCbxSeccion();
        llenarCbxAlumnos();
        actionSeccionActualizar();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CboxCursos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        CboxSecciones = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFechaM = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtestado = new javax.swing.JTextField();
        jComboBoxIDAlumno = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(670, 580));
        setPreferredSize(new java.awt.Dimension(670, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrar.setBackground(new java.awt.Color(102, 102, 255));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("MATRICULAR");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 640, 130, 70));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(96, 131, 165));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PROCESO DE MATRÍCULA");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 530, 70));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("ID Alumno:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 220, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Curso a matricular:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 220, 30));

        CboxCursos.setBackground(new java.awt.Color(255, 255, 255));
        CboxCursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALGEBRA", "CALCULO II", "FISICA", " " }));
        CboxCursos.setBorder(null);
        CboxCursos.setMinimumSize(new java.awt.Dimension(142, 22));
        CboxCursos.setPreferredSize(new java.awt.Dimension(142, 22));
        add(CboxCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 270, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("Sección:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 220, 30));

        CboxSecciones.setBackground(new java.awt.Color(255, 255, 255));
        CboxSecciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        CboxSecciones.setBorder(null);
        CboxSecciones.setPreferredSize(new java.awt.Dimension(142, 22));
        add(CboxSecciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 270, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/Imagenes/Rectangle 5inicio2 (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 430, 540));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setText("Fecha:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 260, -1));

        txtFechaM.setBackground(new java.awt.Color(255, 255, 255));
        txtFechaM.setText("fecha");
        txtFechaM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(txtFechaM, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 270, 40));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        jLabel6.setText("Estado:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 60, -1));

        txtestado.setBackground(new java.awt.Color(255, 255, 255));
        txtestado.setText("Estado");
        txtestado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(txtestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 270, 30));

        jComboBoxIDAlumno.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxIDAlumno.setForeground(new java.awt.Color(204, 204, 255));
        jComboBoxIDAlumno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxIDAlumno.setBorder(null);
        jComboBoxIDAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBoxIDAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIDAlumnoActionPerformed(evt);
            }
        });
        add(jComboBoxIDAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 270, 40));
    }// </editor-fold>//GEN-END:initComponents
   
    //LLENAR CURSOS COMBOBOX
    public void llenarCbxCurso(){
        daoCurso cursos = new daoCurso();
        CboxCursos.removeAllItems();
        ArrayList<Curso> listaCursos = cursos.obtenerLista();
        for(Curso curso : listaCursos){
            CboxCursos.addItem(curso.getNombreCurso());
        }
    }
    
    //LLENAR CURSOS COMBOBOX
    public void llenarCbxSeccion(){
        daoSeccion secciones = new daoSeccion();
        CboxSecciones.removeAllItems();
        
        int idCurso = obtenerIDcurso();
        
        ArrayList<Seccion> listaSeccion = secciones.obtenerLista();
        for(Seccion seccion : listaSeccion){
            if(seccion.getId_curso()==idCurso)
                CboxSecciones.addItem(seccion.getNombreSeccion());
            
        }
    }

    //LLENAR CURSOS COMBOBOX
    public void llenarCbxAlumnos(){
        daoUsuario listaAlumno = new daoUsuario();
        jComboBoxIDAlumno.removeAllItems();
        ArrayList<Alumno> listaAlumnos = listaAlumno.obtenerListaAlumno();
        for(Alumno alumno : listaAlumnos){
            jComboBoxIDAlumno.addItem(alumno.getNombre());
        }
            
        
    }

    public int obtenerIDAlumno(){
        daoUsuario dao = new daoUsuario();
        ArrayList<Alumno> lista = dao.obtenerListaAlumno();
        for(Alumno alumno : lista){
            if(alumno.getNombre().equals(jComboBoxIDAlumno.getSelectedItem())){
                return alumno.getId_alumno();
            }
        }
        return 0;
    }
    
    public int obtenerIDcurso(){
        int idCurso=0;
        daoCurso cursos = new daoCurso();
        ArrayList<Curso> listaCursos = cursos.obtenerLista();
        for(Curso curso : listaCursos){
            if(curso.getNombreCurso().equals(CboxCursos.getSelectedItem())){
                idCurso = curso.getId_curso();
            }
        }
        return idCurso;
    }
    
    public int obtenerIDseccion(){

        daoSeccion secc = new daoSeccion();
        ArrayList<Seccion> listaSecciones = secc.obtenerLista();
        for(Seccion seccion : listaSecciones){
            if(seccion.getNombreSeccion().equals(CboxSecciones.getSelectedItem())){
                return seccion.getId_seccion();
            }
        }
        return 0;
    }
    
    //ActionListener para los combobox 
    public void actionSeccionActualizar(){
        CboxCursos.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Cuando cambia la selección en el ComboBox de curso, actualiza el ComboBox de sección
                llenarCbxSeccion();
            }
        });
    }
    
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        try {
        int idEstudiante, idseccion;
        idEstudiante = obtenerIDAlumno();
        idseccion = obtenerIDseccion();
        daoMatrícula matricula = new daoMatrícula();

        // Verificar si el alumno ya está matriculado en esa sección
        if (matricula.alumnoYaMatriculado(idEstudiante, idseccion)) {
            throw new Exception("Alumno ya matriculado");
        } else {
            // Realizar la matrícula solo si el alumno no está matriculado en esa sección
            Matricula m1 = new Matricula(3, idseccion, idEstudiante, txtFechaM.getText(), txtestado.getText());

            if (matricula.realizarMatricula(m1)) {
                System.out.println("Se realizó la matrícula exitosamente");
            } else {
                throw new Exception("Error al realizar matrícula");
            }
        }
    } catch (Exception e) {
        mostrarErrorDialog(e.getMessage());
        
    }
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void mostrarErrorDialog(String errorMessage) {
        ErrorDialog errorDialog = new ErrorDialog(errorMessage);
        errorDialog.setVisible(true);
    }
    
    private void jComboBoxIDAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIDAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxIDAlumnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboxCursos;
    private javax.swing.JComboBox<String> CboxSecciones;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> jComboBoxIDAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtFechaM;
    private javax.swing.JTextField txtestado;
    // End of variables declaration//GEN-END:variables
}
