/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package Sistemas.Reportes;

import Sistema.Clases.Usuario;
import Sistema.Clases.daoUsuario;
import Sistema.Frames.Tablas.TableDesigner;
import Sistema.Frames.Tablas.actualizarTablaGenérica;

/**
 *
 * @author Jorge
 */
public class ReporteUsuarios extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;
    daoUsuario daousuario = new daoUsuario();
    /**
     * Creates new customizer ReporteUsuarios
     */
    public ReporteUsuarios() {
        initComponents();
        TableDesigner tabla = new TableDesigner();
        tabla.designTable(Usuarios);
        Actualizar();
    }
    public void Actualizar(){
        actualizarTablaGenérica<Usuario> actualizar = new actualizarTablaGenérica<>();
        String[] columna = {"Id_Usuario","nombre","Edad","teléfono","Nivel"};
        actualizar.actualizarTabla(daousuario.obtenerLista(), columna, Usuarios);
    }
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Usuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "ttitulo5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Usuarios.setRowHeight(40);
        Usuarios.setSelectionBackground(new java.awt.Color(204, 204, 204));
        Usuarios.setSelectionForeground(new java.awt.Color(255, 255, 255));
        Usuarios.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(Usuarios);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 530, 430));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(96, 131, 165));
        jLabel1.setText("MENU USUARIOS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 269, 39));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable Usuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
