/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Sistema.MatriculaPrueba;

import Sistema.Clases.Curso;
import Sistema.Clases.Seccion;
import Sistema.Clases.daoCurso;
import Sistema.Clases.daoSeccion;
import java.util.ArrayList;

/**
 *
 * @author User
 */
public class SeccionPanel extends javax.swing.JPanel {

    /**
     * Creates new form SeccionPanel
     */
    public SeccionPanel() {
        initComponents();
        llenarComboBoxCursos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        lblName = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        lblHorario1 = new javax.swing.JLabel();
        tfHorario = new javax.swing.JTextField();
        lblCurso = new javax.swing.JLabel();
        cbCurso = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jbProfesor = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setBackground(new java.awt.Color(255, 255, 255));

        lblName.setText("Nombre de la seccion :");

        tfName.setText("jTextField1");

        lblHorario1.setText("Horario");

        tfHorario.setText("jTextField1");

        lblCurso.setText("Curso");

        cbCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCursoActionPerformed(evt);
            }
        });

        jLabel1.setText("Profesor");

        jbProfesor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("AGREGAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jbProfesor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addComponent(lblHorario1)
                        .addComponent(tfHorario, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                        .addComponent(lblCurso)
                        .addComponent(lblName)
                        .addComponent(tfName)
                        .addComponent(cbCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblHorario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCursoActionPerformed
        
    }//GEN-LAST:event_cbCursoActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            int id_curso = obtenerIDCurso();
            Seccion seccion = new Seccion(0, tfName.getText(), id_curso, 0, tfHorario.getText());
            
            daoSeccion seccionDAO = new daoSeccion();
            if(seccionDAO.agregarSeccion(seccion)){
                System.out.println("Se agregó seccion");
            } else {
                throw new Exception("No se pudo abrir seccion");
            }
        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_jButton1MouseClicked
    
    
    //LLENAR COMBOBOX DE CURSOS
    public void llenarComboBoxCursos(){
        daoCurso cursos = new daoCurso();
        cbCurso.removeAllItems();
        ArrayList<Curso> listaCursos = cursos.obtenercrusos();
        for(Curso curso : listaCursos){
            cbCurso.addItem(curso.getNombreCurso());
        }
    }
    
    //OBTNER ID DEL CURSO
    public int obtenerIDCurso(){

        daoCurso cursos = new daoCurso();
        ArrayList<Curso> listaCursos = cursos.obtenercrusos();
        for(Curso curso : listaCursos){
            if(cbCurso.getSelectedItem().equals(curso.getNombreCurso())) {
                return curso.getId_curso();
            }
        }
        return 0;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCurso;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JComboBox<String> jbProfesor;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblHorario1;
    private javax.swing.JLabel lblName;
    private javax.swing.JTextField tfHorario;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
